"use strict";
const DEFAULT_KEYWORDS = [
  "artificial intelligence",
  "machine learning",
  "deep learning",
  "neural network",
  "neural networks",
  "large language model",
  "large language models",
  "generative ai",
  "gen ai",
  "genai",
  "conversational ai",
  "predictive ai",
  "responsible ai",
  "explainable ai",
  "multimodal ai",
  "agentic ai",
  "narrow ai",
  "chatgpt",
  "gpt-3",
  "gpt-4",
  "gpt-4o",
  "gpt-5",
  "gpt3",
  "gpt4",
  "gpt5",
  "openai",
  "claude",
  "claude 3",
  "claude 4",
  "gemini",
  "gemini pro",
  "gemini ultra",
  "copilot",
  "github copilot",
  "microsoft copilot",
  "midjourney",
  "dall-e",
  "dall·e",
  "stable diffusion",
  "stability ai",
  "llama",
  "llama 3",
  "mistral",
  "mixtral",
  "perplexity",
  "anthropic",
  "deepseek",
  "sora",
  "grok",
  "cohere",
  "hugging face",
  "huggingface",
  "replicate",
  "runway",
  "runway ml",
  "jasper ai",
  "notion ai",
  "grammarly ai",
  "adobe firefly",
  "firefly",
  "meta ai",
  "google bard",
  "bard",
  "character.ai",
  "inflection ai",
  "pi ai",
  "claude code",
  "cursor ai",
  "windsurf",
  "codeium",
  "tabnine",
  "amazon q",
  "aws bedrock",
  "vertex ai",
  "azure openai",
  "together ai",
  "anyscale",
  "mosaic ml",
  "databricks ai",
  "snowflake cortex",
  "langchain",
  "llamaindex",
  "crewai",
  "autogen",
  "semantic kernel",
  "ai-powered",
  "ai powered",
  "ai-driven",
  "ai driven",
  "ai-enabled",
  "ai enabled",
  "ai-first",
  "ai first",
  "ai-native",
  "ai native",
  "ai tool",
  "ai tools",
  "ai agent",
  "ai agents",
  "ai startup",
  "ai startups",
  "ai revolution",
  "ai disruption",
  "ai transformation",
  "ai will replace",
  "ai is coming",
  "ai is taking over",
  "ai is changing",
  "ai is transforming",
  "ai is revolutionizing",
  "replaced by ai",
  "future of ai",
  "age of ai",
  "power of ai",
  "prompt engineering",
  "prompt engineer",
  "prompt injection",
  "vibe coding",
  "ai coding",
  "ai wrapper",
  "ai productivity",
  "ai automation",
  "ai workflow",
  "ai workflows",
  "10x with ai",
  "leverage ai",
  "leveraging ai",
  "harness ai",
  "harnessing ai",
  "embrace ai",
  "embracing ai",
  "adopt ai",
  "adopting ai",
  "ai skills",
  "ai literacy",
  "ai strategy",
  "ai roadmap",
  "ai hype",
  "ai bubble",
  "ai gold rush",
  "ai arms race",
  "ai winter",
  "llm",
  "llms",
  "agi",
  "asi",
  "nlp",
  "rag",
  "gpt",
  "rlhf",
  "aigc",
  "aiml",
  "transformer model",
  "transformer architecture",
  "foundation model",
  "foundation models",
  "diffusion model",
  "diffusion models",
  "fine-tuning",
  "fine tuning",
  "finetuning",
  "retrieval augmented",
  "vector database",
  "vector search",
  "vector embedding",
  "embeddings",
  "tokenizer",
  "tokenization",
  "inference",
  "model training",
  "model deployment",
  "model serving",
  "text-to-image",
  "text to image",
  "text-to-video",
  "text to video",
  "text-to-speech",
  "text to speech",
  "speech-to-text",
  "image generation",
  "video generation",
  "code generation",
  "ai governance",
  "ai ethics",
  "ai safety",
  "ai alignment",
  "ai bias",
  "ai fairness",
  "ai hallucination",
  "hallucinations",
  "superintelligence",
  "ai regulation",
  "ai policy",
  "ai act",
  "compute cluster",
  "gpu cluster",
  "training data",
  "synthetic data",
  "data labeling",
  "data annotation",
  "reinforcement learning",
  "computer vision",
  "natural language processing",
  "knowledge graph",
  "attention mechanism",
  "chain of thought",
  "zero-shot",
  "few-shot",
  "in-context learning",
  "model collapse",
  "benchmark",
  "leaderboard",
  "open source ai",
  "open-source ai",
  "ai chip",
  "ai chips",
  "neural processing",
  "tensor processing",
];
const KEYWORDS_VERSION = 2;
